# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d462164a8b3f5096fbde0215e7aacae6"
name = "Puppies & Yoga Manager Custom"
handle = "puppies-yoga-manager-custom"
application_url = "https://puppies-yoga-manager-staging-2cb219823a54.herokuapp.com/"
embedded = true

[auth]
redirect_urls = [ "https://puppies-yoga-manager-staging-2cb219823a54.herokuapp.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_orders,read_all_orders"

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
